"""Golden hashes of the GIZMO sources generated for every registered model.

Refactors that must not change the generated code are checked against tests/golden_codegen.json. After an
intended change to a model or to the code generator, regenerate the hashes and commit them with the change:

    UPDATE_GOLDEN=1 python -m pytest tests/test_golden_codegen.py

Each model is generated by the CLI in its own interpreter, all models concurrently (minutes in total), so the test
is marked slow: deselect it with -m "not slow".
"""

import hashlib
import json
import os
import pkgutil
import subprocess
import sys
from importlib import import_module
from pathlib import Path

import numpy as np
import pytest

import jaco
import jaco.models

GOLDEN = Path(__file__).with_name("golden_codegen.json")
UPDATE = os.environ.get("UPDATE_GOLDEN") == "1"
TIMEOUT = 900  # seconds per model


def registered_models():
    """Subpackages of jaco.models that provide make_model(), i.e. what the CLI accepts"""
    return sorted(m.name for m in pkgutil.iter_modules(jaco.models.__path__)
                  if m.ispkg and hasattr(import_module(f"jaco.models.{m.name}"), "make_model"))


def file_digest(path):
    """sha256 of a generated file; for HDF5, of its datasets and attributes rather than the library's byte layout"""
    if path.suffix != ".hdf5":
        return hashlib.sha256(path.read_bytes()).hexdigest()
    import h5py

    h = hashlib.sha256()

    def update(name, value):
        value = np.asarray(value)
        h.update(f"{name}:{value.dtype.str}:{value.shape}".encode())
        h.update(np.ascontiguousarray(value).tobytes())

    with h5py.File(path, "r") as f:
        for obj in [f] + [f[name] for name in sorted(f)]:
            if obj is not f:
                update(obj.name, obj[()])
            for key in sorted(obj.attrs):
                update(f"{obj.name}@{key}", obj.attrs[key])
    return h.hexdigest()


@pytest.fixture(scope="module")
def generated(tmp_path_factory):
    """Launch the CLI for every model at once; maps model -> (output dir, Popen, log path)"""
    env = dict(os.environ)
    src = str(Path(jaco.__file__).resolve().parents[1])  # the subprocesses import this jaco, not an installed one
    env["PYTHONPATH"] = os.pathsep.join([src] + [p for p in [env.get("PYTHONPATH")] if p])
    runs = {}
    for model in registered_models():
        out = tmp_path_factory.mktemp(model)
        log = out.with_suffix(".log")
        cmd = [sys.executable, "-m", "jaco.codegen.gizmo.gizmo", model, "--language", "c", "--ext", ".cc",
               "--output-dir", str(out)]
        with open(log, "w") as f:
            runs[model] = (out, subprocess.Popen(cmd, env=env, stdout=f, stderr=subprocess.STDOUT), log)
    yield runs
    for _, proc, _ in runs.values():
        if proc.poll() is None:
            proc.kill()


def update_golden(model, hashes):
    golden = json.loads(GOLDEN.read_text()) if GOLDEN.exists() else {}
    golden[model] = hashes
    golden = {m: golden[m] for m in registered_models() if m in golden}
    GOLDEN.write_text(json.dumps(golden, indent=2, sort_keys=True) + "\n")


@pytest.mark.slow
@pytest.mark.parametrize("model", registered_models())
def test_generated_sources_match_golden(model, generated):
    out, proc, log = generated[model]
    try:
        returncode = proc.wait(timeout=TIMEOUT)
    except subprocess.TimeoutExpired:
        proc.kill()
        pytest.fail(f"codegen for {model} did not finish in {TIMEOUT} s")
    assert returncode == 0, f"codegen for {model} failed:\n" + "".join(log.read_text().splitlines(True)[-30:])
    hashes = {p.name: file_digest(p) for p in sorted(out.iterdir())}

    if UPDATE:
        update_golden(model, hashes)
        return
    golden = json.loads(GOLDEN.read_text()) if GOLDEN.exists() else {}
    assert model in golden, f"no golden hashes for {model}; regenerate with UPDATE_GOLDEN=1"
    changed = sorted(n for n in hashes.keys() | golden[model].keys() if hashes.get(n) != golden[model].get(n))
    assert not changed, (f"generated sources for {model} differ from the golden hashes in {changed} (output kept in "
                         f"{out}); if the change is intended, regenerate with UPDATE_GOLDEN=1")
