"""Write the jaco-generated microphysics sources that GIZMO's JACO build compiles.

Artifact set (C, with source extension ``ext``):

- ``microphysics_func_jac{ext}`` -- RHS + analytic Jacobian of the backward-Euler system
- ``microphysics_func_jac.h``    -- SolveVars/Params unions, IDX_/PARAM_ enums, JACO_MODEL_<NAME>, JACO_FAMILY_<FAMILY>
- ``jaco_interp.h``              -- 1D interpolation helpers and static 1D table data
- ``jaco_eos{ext}``              -- jaco_eos_pressure, jaco_T_to_u, jaco_u_to_T, jaco_electron_abundance,
                                    jaco_fixed_electron_abundance
- ``jaco_tables.h``              -- 2D/3D table types, extern table objects, jaco_init_tables()
- ``jaco_util{ext}``             -- table storage + HDF5 loader, jaco_isfinite()
- ``jaco_tables.hdf5``           -- runtime table data; must sit in the run directory (only if the
                                    model has 2D/3D tables)
"""

import hashlib
import os
import re
from importlib.resources import files

import numpy as np
import sympy as sp

TABLE_FILE = "jaco_tables.hdf5"


def _table_digest(tables):
    """64-bit fingerprint of table names, metadata and data, shared by the code and the HDF5 file."""
    h = hashlib.sha256()
    for name in sorted(tables):
        t = tables[name]
        h.update(name.encode())
        h.update(np.asarray(t["shape"], dtype=np.int64).tobytes())
        for i in range(t["ndim"]):
            h.update(np.array([t[f"axis{i}_min"], t[f"axis{i}_max"]], dtype="<f8").tobytes())
            h.update(bytes([int(t["log_axes"][i])]))
        h.update(np.ascontiguousarray(t["data"], dtype="<f8").tobytes())
    return int(h.hexdigest()[:16], 16)


def _table_initializer(t):
    """Positional initializer matching the JacoTable2D/3D field order in jaco_table.h."""
    nd = t["ndim"]
    ranges = ", ".join(f"{t[f'axis{i}_min']!r}, {t[f'axis{i}_max']!r}" for i in range(nd))
    shape = ", ".join(str(n) for n in t["shape"])
    logs = ", ".join(str(int(b)) for b in t["log_axes"])
    return f"{{NULL, {ranges}, {shape}, {logs}}}"


def _gen_tables_header(tables):
    table_h = files("jaco.codegen").joinpath("jaco_table.h").read_text()
    table_h = table_h.replace("#pragma once\n", "", 1)
    lines = [
        "#pragma once",
        "/* Generated by jaco codegen. 2D/3D interpolation tables; data is loaded at startup by",
        f"   jaco_init_tables() from <dir>/{TABLE_FILE}. */",
        table_h,
    ]
    for name, t in tables.items():
        lines.append(f"extern JacoTable{t['ndim']}D {name};")
    lines += [
        "",
        f"/* Load every table from <dir>/{TABLE_FILE}; no-op if the model has none. Aborts if the file is",
        "   missing or was generated for a different build. */",
        "void jaco_init_tables(const char *dir);",
        "",
    ]
    return "\n".join(lines)


_UTIL_COMMON = r"""/* Generated by jaco codegen. Runtime table storage/loading and numerical helpers. */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "jaco_tables.h"
{hdf5_include}
/* Bitwise finiteness test: unlike isfinite(), it survives -ffast-math. */
#ifdef __cplusplus
extern "C"
#endif
int jaco_isfinite(double x) {{
    uint64_t bits;
    memcpy(&bits, &x, sizeof(bits));
    return ((bits >> 52) & 0x7FF) != 0x7FF;
}}
"""

_UTIL_NO_TABLES = r"""
void jaco_init_tables(const char *dir) {
    (void)dir;
}
"""

_UTIL_LOADER = r"""
#define JACO_TABLE_DIGEST {digest:#018x}ULL

{definitions}

static void jaco_table_fatal(const char *path, const char *msg) {{
    fprintf(stderr, "JACO FATAL: %s: %s\n", path, msg);
    fprintf(stderr, "  {table_file} is written by the jaco codegen next to the generated sources (GIZMO: cooling/)\n"
                    "  and must be copied into the run directory from the same build.\n");
    fflush(stderr);
    exit(1);
}}

/* Read dataset `name` into a freshly allocated array, checking it has the shape baked in by codegen. */
static double *jaco_read_table(hid_t file, const char *path, const char *name, int ndim, const int *shape) {{
    hid_t dset = H5Dopen2(file, name, H5P_DEFAULT);
    if (dset < 0) jaco_table_fatal(path, name);
    hid_t space = H5Dget_space(dset);
    hsize_t dims[3] = {{0, 0, 0}};
    size_t n = 1;
    if (H5Sget_simple_extent_ndims(space) != ndim) jaco_table_fatal(path, "table rank mismatch");
    H5Sget_simple_extent_dims(space, dims, NULL);
    for (int i = 0; i < ndim; i++) {{
        if ((int)dims[i] != shape[i]) jaco_table_fatal(path, "table shape mismatch");
        n *= dims[i];
    }}
    double *data = (double *)malloc(n * sizeof(double));
    if (!data || H5Dread(dset, H5T_NATIVE_DOUBLE, H5S_ALL, H5S_ALL, H5P_DEFAULT, data) < 0)
        jaco_table_fatal(path, "failed to read table data");
    H5Sclose(space);
    H5Dclose(dset);
    return data;
}}

void jaco_init_tables(const char *dir) {{
    char path[4096];
    snprintf(path, sizeof(path), "%s/{table_file}", dir);
    hid_t file = H5Fopen(path, H5F_ACC_RDONLY, H5P_DEFAULT);
    if (file < 0) jaco_table_fatal(path, "cannot open table file");
    unsigned long long digest = 0;
    hid_t attr = H5Aopen(file, "digest", H5P_DEFAULT);
    if (attr < 0 || H5Aread(attr, H5T_NATIVE_ULLONG, &digest) < 0) jaco_table_fatal(path, "no digest attribute");
    H5Aclose(attr);
    if (digest != JACO_TABLE_DIGEST) jaco_table_fatal(path, "digest does not match the compiled tables");
{loads}
    H5Fclose(file);
}}
"""


def _gen_util_source(tables):
    if not tables:
        return _UTIL_COMMON.format(hdf5_include="") + _UTIL_NO_TABLES
    definitions = "\n".join(f"JacoTable{t['ndim']}D {name} = {_table_initializer(t)};" for name, t in tables.items())
    loads = []
    for name, t in tables.items():
        shape = ", ".join(str(n) for n in t["shape"])
        loads.append(f"    {{ const int shape[] = {{{shape}}}; "
                     f"{name}.data = jaco_read_table(file, path, \"{name}\", {t['ndim']}, shape); }}")
    loader = _UTIL_LOADER.format(digest=_table_digest(tables), definitions=definitions,
                                 table_file=TABLE_FILE, loads="\n".join(loads))
    return _UTIL_COMMON.format(hdf5_include="#include <hdf5.h>\n") + loader


def _write_tables_hdf5(tables, path):
    import h5py

    with h5py.File(path, "w") as f:
        f.attrs["digest"] = np.uint64(_table_digest(tables))
        for name, t in tables.items():
            dset = f.create_dataset(name, data=np.ascontiguousarray(t["data"], dtype=np.float64))
            for i, ax in enumerate(t["axes"]):
                dset.attrs[f"axis{i}"] = ax
                dset.attrs[f"axis{i}_log"] = int(t["log_axes"][i])


def _write_if_changed(path, text):
    """Write text to path, leaving the file (and its mtime) alone if the content is unchanged."""
    if os.path.isfile(path):
        with open(path) as f:
            if f.read() == text:
                return
    with open(path, "w") as f:
        f.write(text)


def generate_funcjac_code(
    system,
    solve_vars=None,
    time_dependent=None,
    cse=True,
    language="c",
    jac_mode="symbolic",
    func_name="microphysics_func_jac",
    source_ext=None,
    output_dir=".",
    model_name=None,
    model_family=None,
):
    """Generate the RHS + Jacobian sources for ``system`` and write them to ``output_dir``.

    Prints every equation the reduction discards, with the reason. Refuses any symbol the model does not declare.

    Parameters
    ----------
    system : Model
        The model to generate code for. Must already include any PdV-work term it needs.
    solve_vars : list of str, optional
        Solve variables in index order; the model's own by default.
    time_dependent : list of str, optional
        Variables that get a backward-Euler term; the model's own by default.
    cse : bool
        Apply common subexpression elimination.
    language : str
        'c', 'c++', 'cuda', 'python' or 'julia'. The table/runtime glue (jaco_tables.h, jaco_util)
        is only emitted for 'c'.
    jac_mode : str
        'symbolic' (explicit Jacobian) or 'autodiff' (forward-mode duals; C++/CUDA only).
    func_name : str
        Name of the generated RHS + Jacobian function.
    source_ext : str, optional
        Source file extension (e.g. '.cc'); defaults to the language's usual one.
    output_dir : str
        Directory to write into.
    model_name : str, optional
        If given, the header defines JACO_MODEL_<MODEL_NAME> for host-code #ifdefs.
    model_family : str, optional
        If given (or with model_name, which is its default), the header also defines JACO_FAMILY_<MODEL_FAMILY>, which
        models sharing the host code's paths have in common.
    """
    from ...model import Model

    if not isinstance(system, Model):
        raise TypeError("generate code for a Model, which declares the solve variables, parameters and species")
    if not system.species:
        raise ValueError("the model declares no species; code generation needs them to check its symbols")
    solve_vars = system.solve_vars if solve_vars is None else solve_vars
    time_dependent = system.time_dependent if time_dependent is None else time_dependent
    if not solve_vars:
        raise ValueError("no solve variables")
    solve_vars, time_dependent = list(solve_vars), list(time_dependent)
    lang = language.lower()
    if source_ext is None:
        source_ext = {"c": ".c", "c++": ".cpp", "cuda": ".cu", "python": ".py", "julia": ".jl"}[lang]
    os.makedirs(output_dir, exist_ok=True)

    if sp.Symbol("pdv_work") not in system.heat.free_symbols:
        raise ValueError("model has no pdv_work term; add ThermalProcess(sp.Symbol('pdv_work')) to it")

    result = system.network.generate_code(
        solve_vars, time_dependent, language=language, jac=True, do_cse=cse,
        minimal=False, func_name=func_name, jac_mode=jac_mode,
    )
    code = result["code"]
    if result.get("discarded"):
        print("jaco codegen: discarded equations: "
              + ", ".join(f"{k} ({why})" for k, why in result["discarded"].items()))
    # Only the tables the generated code actually references (the registry is process-global)
    tables = {name: t for name, t in result.get("tables", {}).items() if re.search(rf"&{re.escape(name)}\b", code)}

    def out(name, text):
        _write_if_changed(os.path.join(output_dir, name), text)

    out(func_name + source_ext, code)
    if "header" in result:
        header = result["header"]
        if model_name:
            macros = ["JACO_MODEL_" + re.sub(r"\W", "_", model_name).upper(),
                      "JACO_FAMILY_" + re.sub(r"\W", "_", model_family or model_name).upper()]
            header = header.replace("#pragma once\n", "#pragma once\n" + "".join(f"#define {m}\n" for m in macros), 1)
        out(func_name + ".h", header)
    if lang in ("c", "c++", "cuda"):
        out("jaco_interp.h", "#pragma once\n" + result.get("interp_header", "") + "\n")
    if "eos_code" in result:
        out("jaco_eos" + source_ext, result["eos_code"])
    if lang == "c":
        out("jaco_tables.h", _gen_tables_header(tables))
        out("jaco_util" + source_ext, _gen_util_source(tables))

    table_path = os.path.join(output_dir, TABLE_FILE)
    if tables:
        _write_tables_hdf5(tables, table_path)
    elif os.path.exists(table_path):
        os.remove(table_path)
    return result
